import type { Metadata } from "next";
import "@repo/ui/globals.css";
import type { ReactElement } from "react";
import { Footer } from "../components/footer";
import { Header } from "../components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: ReactElement }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={"bg-[#0C0C0C] text-slate-200 overflow-x-hidden antialiased"}
      >
        <Header />
        <main className="container mx-auto px-4 overflow-hidden md:overflow-visible">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
