name: Promote to Main

on:
  push:
    tags:
      - 'v*.*.*-preprod'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_GITHUB_PROFILE_URL=${{ secrets.NEXT_PUBLIC_GITHUB_PROFILE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_LINKEDIN_PROFILE_URL=${{ secrets.NEXT_PUBLIC_LINKEDIN_PROFILE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_TRPC_URL=${{ secrets.NEXT_PUBLIC_TRPC_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install


      - name: Check if major update
        id: check_major
        run: |
          VERSION=$(pnpm version | grep -oP '(?<=version": ")[^"]+')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          if [ "$MINOR" -eq "0" ] && [ "$PATCH" -eq "0" ]; then
            echo "::set-output name=major_update::true"
          else
            echo "::set-output name=major_update::false"
          fi

      - name: Merge to main
        if: steps.check_major.outputs.major_update == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git merge dev
          git push origin main